### ISSUE TITLE
npm run build:win can't login

### ISSUE THREAD

**Issue by jishufangui** [mxin-d/electron-admin#1]
when I run build:win , it can't login to homepage.

**Comment by mxin-d** [comment]
打包时候把浏览器控制台开启，看下错误日志是什么

**Comment by mxin-d** [comment]
> when I run build:win , it can't login to homepage.

打包时候把浏览器控制台开启，看下错误日志是什么

**Comment by jishufangui** [comment]
> > when I run build:win , it can't login to homepage.
> 
> 打包时候把浏览器控制台开启，看下错误日志是什么

没有报错，执行this.$router.push 没有反应。

**Comment by jishufangui** [comment]
> > > when I run build:win , it can't login to homepage.
> > 
> > 
> > 打包时候把浏览器控制台开启，看下错误日志是什么
> 
> 没有报错，执行this.$router.push 没有反应。

用mock是直接打包时可以，带真实接口没法调转

**Comment by mxin-d** [comment]
> > > > when I run build:win , it can't login to homepage.
> > > 
> > > 
> > > 打包时候把浏览器控制台开启，看下错误日志是什么
> > 
> > 
> > 没有报错，执行this.$router.push 没有反应。
> 
> 用mock是直接打包时可以，带真实接口没法调转

最好先梳理一下之前的登录逻辑，首先保证你的登录逻辑正确，vuex修改状态后处理路由时路由是否工作正常，包括`this.redirect`重定向的路径内容，不报错的情况下就得自己排查一下，可以看下vue-devtools调试工具，已经集成了，我这边没遇到过这种情况

**Comment by jishufangui** [comment]
> > > > > when I run build:win , it can't login to homepage.
> > > > 
> > > > 
> > > > 打包时候把浏览器控制台开启，看下错误日志是什么
> > > 
> > > 
> > > 没有报错，执行this.$router.push 没有反应。
> > 
> > 
> > 用mock是直接打包时可以，带真实接口没法调转
> 
> 最好先梳理一下之前的登录逻辑，首先保证你的登录逻辑正确，vuex修改状态后处理路由时路由是否工作正常，包括`this.redirect`重定向的路径内容，不报错的情况下就得自己排查一下，可以看下vue-devtools调试工具，已经集成了，我这边没遇到过这种情况

感谢回复，我生产环境把vueroute错误屏蔽了，感觉好像是vueroute 版本导致的。
![微信截图_20201027105139](https://user-images.githubusercontent.com/15605454/97251150-4cc7c200-1842-11eb-9047-cb8922544d42.png)
Redirected when going from "/login?redirect=%2Fdashboard" to "/dashboard" via a navigation guard

**Comment by jishufangui** [comment]
这个问题是发布win后无法获得cookie 导致验证不过

**Comment by mxin-d** [comment]
> 这个问题是发布win后无法获得cookie 导致验证不过

ok
