### ISSUE TITLE
登录进入首页，选项卡路由信息异常

### ISSUE THREAD

**Issue by gengsende** [mxin-d/electron-admin#2]
您好，我在执行完如下命令
`npm i`

`npm run dev`
进入首页，点击登录后，菜单栏出现
![image](https://user-images.githubusercontent.com/23625903/101557806-af42df00-39f8-11eb-9b8b-449c3b554650.png)

没有默认选中首页的选项卡
而且我在（路径 src\renderer\layout\components\TagsView\index.vue）打印选项卡路由数组时，显示如下
![image](https://user-images.githubusercontent.com/23625903/101558074-2e381780-39f9-11eb-8de5-7a943ca5315a.png)

因为路由信息不对，点击前两项会跳转404页面。。

希望您能指点下，不胜感激！

**Comment by mxin-d** [comment]
@gengsende 看样子好像是根路由指向错误，看下router/index.js中如何配置的

**Comment by gengsende** [comment]
![image](https://user-images.githubusercontent.com/23625903/101568537-b1636880-3a0d-11eb-846f-7d668154886d.png)
![image](https://user-images.githubusercontent.com/23625903/101568638-e5d72480-3a0d-11eb-93d0-a5ead7004d98.png)
我发现是path.resolve执行后就有问题了，是不是webpack配置问题？

**Comment by mxin-d** [comment]
@gengsende path.resolve把你的路径转成了D:\ + route.path，应该是这个问题，换个api拼接试试，而且windows下在操作路径时要注意‘/’和'\\'是有区别的，我们不是去查找文件，只是拼接一个路由字符串

**Comment by gengsende** [comment]
您好好，我把 `path.resolve()`  换成了`path.posix.join()`,然后运行正常了。
